const actions = {
  SHOW_LOG_IN : 'SHOW_LOG_IN',
  INIT_LOG_IN : 'INIT_LOG_IN',
  LOG_IN_SUCCESS : 'LOG_IN_SUCCESS',
  LOG_IN_ERROR : 'LOG_IN_ERROR',

  SHOW_SIGN_UP : 'SHOW_SIGN_UP',
  INIT_SIGN_UP : 'INIT_SIGN_UP',
  SIGN_UP_ERROR : 'SIGN_UP_ERROR',

  INIT_LOGOUT : 'INIT_LOGOUT',

  INIT_FETCH : 'INIT_FETCH',
  POST_FETCH : 'POST_FETCH',
  NEW_POST : 'NEW_POST'
}

export default actions;
